---
- name: Setup Node.js Application with MongoDB Atlas
  hosts: all
  become: yes
  tasks:
    - name: install nodejs and npm on ubuntu
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        update_cache: yes
        state: present
    - name: Create Node.js application directory
      ansible.builtin.file:
        path: /home/jenkins/app/
        state: directory
    - name: initializing npm
      ansible.builtin.shell:
        cmd: npm init -y
        chdir: /home/jenkins/app/
    - name: Install NPM packages
      ansible.builtin.shell:
        cmd: npm install express mongoose@6
        chdir: /home/jenkins/app/
    - name: Deploy Node.js Application
      ansible.builtin.copy:
        src:  /home/jenkins/app/app.js
        dest: /home/jenkins/app/
    - name: Starting Node.js Application
      ansible.builtin.shell:
        cmd: nohup node app.js &
        chdir: /home/jenkins/app/
      async: 45
      poll: 0